### ISSUE TITLE
Fatal error on non-numerical quantity

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-gravityforms#40]
A fatal error occurs when a non-numerical value is provided as quantity.

```
PHP Fatal error:  Uncaught InvalidArgumentException: No numerical value: 1 box. in /wp-content/plugins/pronamic-pay-premium/packages/pronamic/wp-number/src/Number.php:442

Stack trace:
#0 /wp-content/plugins/pronamic-pay-premium/packages/pronamic/wp-number/src/Number.php(472): Pronamic\WordPress\Number\Number::parse_string('1 box')
#1 /wp-content/plugins/pronamic-pay-premium/packages/pronamic/wp-number/src/Number.php(320): Pronamic\WordPress\Number\Number::parse_mixed('1 box')
#2 /wp-content/plugins/pronamic-pay-premium/packages/wp-pay-extensions/gravityforms/src/Processor.php(359): Pronamic\WordPress\Number\Number::from_mixed('1 box')
#3 /wp-includes/class-wp-hook.php(326): Pronamic\WordPress\Pay\Extensions\GravityForms\Processor->entry_post_save(Array, Array)
#4 /wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#5 /wp-content/plugins/gravityforms/gravityforms.php(7031): apply_filters('gform_entry_pos...', Array, Array, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
#6 /wp-content/plugins/gravityforms/form_display.php(1932): gf_apply_filters('gform_entry_pos...', Array, Array)
#7 /wp-content/plugins/gravityforms/form_display.php(196): GFFormDisplay::handle_submission(Array, Array, false)
#8 /wp-content/plugins/gravityforms/gravityforms.php(869): GFFormDisplay::process_form(4, 1)
#9 /wp-includes/class-wp-hook.php(324): GFForms::maybe_process_form(Object(WP))
#10 /wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#11 /wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#12 /wp-includes/class-wp.php(830): do_action_ref_array('wp', Array)
#13 /wp-includes/functions.php(1336): WP->main('')
#14 /wp-blog-header.php(16): wp()
#15 /index.php(17): require('wp-blog-header.php')
#16 {main}
  thrown in /wp-content/plugins/pronamic-pay-premium/packages/pronamic/wp-number/src/Number.php on line 442
```

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/2568111710/27116_

**Comment by rvdsteege** [comment]
I think there is little use for us in storing the non-numerical amount? But a 'parser' like suggested seems like a good solution.

However, I know you're not a big fan of `preg_match()` 😉 Should we use that or `explode()` + `is_numeric()` or something? (which probably gives less good results)

**Comment by remcotolsma** [comment]
I'm not a fan of using complex regular expressions that are difficult to understand. Especially if it can also be solved with some string functions. In this case, a regular expression can be quite useful. However, I was still thinking about how we can properly handle decimal and thousand separators.

- `2,5 stuks`
- `2,500 stuks`
- `2.500` stuks`
- `2.500,50 stuks`
- `0,000017 BTC`
- `0,00037 ETH`
- `0,037 ETH`
- `2,037 ETH`
- `2,721.51 EUR`

We need to know the decimal and thousand separators to be able to parse a text properly? Doesn't https://github.com/pronamic/wp-number/blob/main/src/Parser.php already take care of this for us?
